version: '3.8'

networks:
  kcnet:
    driver: bridge

services:
  postgresql:
    image: postgres:14.10
    container_name: handi-hub-postgresql
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - kcnet
    ports:
      - 5432:5432

  keycloak:
    container_name: handi-hub-keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      # KC_LOG_LEVEL: DEBUG
      KC_PROXY: edge
      KC_DB: dev-file
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 8443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: /auth
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:8443:8443
    command: [ 'start', '--import-realm' ]
    networks:
      - kcnet