version: '3.8'

services:
  keycloak:
    container_name: handi-hub-keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      # KC_LOG_LEVEL: DEBUG
      KC_PROXY: edge
      KC_DB: dev-file
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 8443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:8443:8443
    command: [ 'start-dev' ]